### ISSUE TITLE
Error: Cannot find module '/Users/[USERNAME]/.doautomator.json'

### ISSUE THREAD

**Issue by julienma** [bessbd/do-automatinator#1]
After having cloned the repo in ~/.do-automatinator, I tried to `coffee app.coffee settoken <your digitalocean token>`.

However I got this error:

```
Error: Cannot find module '/Users/julien/.doautomator.json'
  at Function.Module._resolveFilename (module.js:337:15)
  at Function.Module._load (module.js:287:25)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/Users/julien/.do-automatinator/app.coffee:4:10)
  at Object.<anonymous> (/Users/julien/.do-automatinator/app.coffee:2:1)
  at Module._compile (module.js:435:26)
  at Object.exports.run (/Users/julien/.do-automatinator/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/Users/julien/.do-automatinator/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/Users/julien/.do-automatinator/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/Users/julien/.do-automatinator/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/Users/julien/.do-automatinator/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:136:18)
  at node.js:963:3
```

I tried creating the file `touch ~/.doautomator.json`, and then got this error:

```
SyntaxError: /Users/julien/.doautomator.json: Unexpected end of input
  at Object.parse (native)
  at Object.Module._extensions..json (module.js:450:27)
  at Module.load (/Users/julien/.do-automatinator/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/Users/julien/.do-automatinator/app.coffee:4:10)
  at Object.<anonymous> (/Users/julien/.do-automatinator/app.coffee:2:1)
  at Module._compile (module.js:435:26)
  at Object.exports.run (/Users/julien/.do-automatinator/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/Users/julien/.do-automatinator/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/Users/julien/.do-automatinator/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/Users/julien/.do-automatinator/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/Users/julien/.do-automatinator/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:136:18)
  at node.js:963:3
```

**Comment by julienma** [comment]
Update: manually adding content in the `~/.doautomator.json` works:

```
{"token":"[MY_TOKEN]"}
```

**Comment by bessbd** [comment]
So... Is the issue to be closed as resolved?

**Comment by julienma** [comment]
Well, one still have to create and populate that file manually.
I'd say either do that in the settoken function, or explain in the readme exactly what to do to create this file.

**Comment by bessbd** [comment]
@julienma: it really was a bug. I've just committed a quick workaround. If you (or anyone you know) has time to fix it better, pull requests are welcome.

**Comment by julienma** [comment]
Works great @bessbd, thanks. :+1:
